version: "3"

services:
  app:
    build:
      context: . 
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c " python manage.py wait_for_db && 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000" 
    environment:
      - DB_HOST=db
      - DB_NAME=app # change to whatever username you want
      - DB_USER=postgres # change to whatever username you want
      - DB_PASS=Apassword123 #change to the password you want for user  
    depends_on:
      - db 

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres # change to whatever username you want
      - POSTGRES_PASSWORD=Apassword123 #change to the password you want for user
    